# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Tremor_v0.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tremor_v0.0

end

target 'Tremor_v0.0 Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tremor_v0.0 Watch App

end
